### ISSUE TITLE
Auto updates are failing

### ISSUE THREAD

**Issue by jcoyne** [LD4P/sinopia_editor#2430] opened 2020-09-08 14:56 UTC
https://sul-ci-prod.stanford.edu/job/SUL-DLSS/job/access-update-scripts/job/master/197/execution/node/29/log/
```
Switched to a new branch 'update-dependencies'
HEAD is now at ada3b4ae Merge pull request #2428 from LD4P/error_messages
npm ERR! Unexpected end of JSON input while parsing near '...-fontawesome-0.0.16.t'

npm ERR! A complete log of this run can be found in:
npm ERR!     /usr/share/tomcat8/.npm/_logs/2020-09-07T09_39_18_148Z-debug.log
ERROR UPDATING sinopia_editor
```

**Comment by justinlittman** [comment] 2020-09-09 13:09
Hmmm, I can't reproduce this locally.

**Comment by michelleif** [comment] 2021-07-20 19:15
can we close this

**Closed** 2021-07-20 19:23 UTC
