### ISSUE TITLE
"New literals" need to be objects associated with URIs

### ISSUE THREAD

**Issue by NancyL** [LD4P/sinopia_editor#2142] opened 2020-04-13 16:44 UTC
When a cataloger does a lookup in Sinopia and there is no match for the term the person is looking for, there is the option to create a "new literal". This is is a nice idea, but it violates the BF model, since the properties for these lookups are object properties, which require a URI, not data properties, which are literals. We need to be able to create these new terms on the fly as we do now, but that new term needs to be associated with a URI as well.

**Comment by michelleif** [comment] 2020-04-22 23:05
see also #1317

**Comment by michelleif** [comment] 2021-02-04 18:13
duplicate of #2339

**Closed by michelleif** 2021-02-04 18:13 UTC
Labels: enhancement
