### ISSUE TITLE
When searching a lookup text disappears when typing stops

### ISSUE THREAD

**Issue by a-cohen** [LD4P/sinopia_editor#1229] opened 2019-08-15 19:23 UTC
In the User Feedback template when I use the lookups in "Publication, Distribution, Manufacture Statements" my text disappears when I stop typing.

The issue persists in both Chrome and Firefox.

**Comment by bushmanb** [comment] 2019-08-15 20:04
This is happening to me as well.

**Comment by justinlittman** [comment] 2019-09-10 16:00
Dupe of #1273.

**Closed by justinlittman** 2019-09-10 16:00 UTC
Labels: BFF, bug
