### ISSUE TITLE
Setting LanguageButton to "No language specified" prevents value from being Indexed

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2090] opened 2020-02-27 17:39 UTC
**Describe the bug**
For an `InputLiteral` component like *bf:mainTitle*, setting the language code with the `LanguageButton` to **No language specified**, results in the field's value not being indexed and searchable in the Sinopia search. 

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Workaround is to set the language code value to an existing language and saving the resource again results in the proper indexing of the resource.

- What environment are you in? (stage or production) production
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
  Firefox on Mac

- If you're cataloging, what Resource Template were you using (name or ID)
**CornellSinatra45:Instance**

**Comment by michelleif** [comment] 2020-03-09 21:21
multiple users experiencing this problem.

**Comment by michelleif** [comment] 2020-03-26 15:24
@jermnelson are we fixing this now? or just recommending that people do not use the "no language specified" option at this time?

**Comment by jermnelson** [comment] 2020-03-26 15:34
> @jermnelson are we fixing this now? or just recommending that people do not use the "no language specified" option at this time?

No, since the work-around exists we haven't prioritized developer resources to work on this issue.

**Comment by michelleif** [comment] 2020-04-02 18:47
closing this as duplicate of LD4P/sinopia_indexing_pipeline#156

**Closed by michelleif** 2020-04-02 18:47 UTC
Labels: BFF, bug
