### ISSUE TITLE
Do a lookup that returns context with the results

### ISSUE THREAD

**Issue by ctenor** [LD4P/sinopia_editor#1231] opened 2019-08-15 20:07 UTC
Not really a bug. The dropdown initially defaults to whatever list you had searched last (e.g. lcsh) before switching to the proper list (naf):

A. Searching NAF. Begins to default to previous lcsh search:  ![8-15-2019 3-47-26 PM](https://user-images.githubusercontent.com/5302543/63123476-11abdc80-bf77-11e9-9dbd-6f9ea598e13d.png)

B. Switches to NAF as desired:  ![8-15-2019 3-49-34 PM](https://user-images.githubusercontent.com/5302543/63123488-18d2ea80-bf77-11e9-9493-bbd371ee9481.png)

**Comment by michelleif** [comment] 2019-09-13 19:45
duplicate of #1282

**Closed by michelleif** 2019-09-13 19:45 UTC
Labels: BFF, bug
