### ISSUE TITLE
Bootstrap 4 follow-up - Make UpdateResourceModal a functional component

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#1560] opened 2019-10-15 21:25 UTC
Currently the `UpdateResourceModal` does not work with Bootstrap 4, need to turn this class into a React functional component with any accompanying changes to `ImportResourceTemplate`  for supporting this modal.

**Comment by jcoyne** [comment] 2019-10-18 01:15
@jermnelson Can you explain " does not work with Bootstrap 4" in what way does it not work?

**Comment by justinlittman** [comment] 2019-10-18 14:19
Dupe of #1577.

**Closed by justinlittman** 2019-10-18 14:19 UTC
Labels: BFF
