### ISSUE TITLE
once id.loc.gov/vocabulary/organizations avail as queryable dataset from QA, add to auth list and update templates

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#2632] opened 2020-10-07 19:11 UTC
This is a placeholder issue for https://github.com/LD4P/qa_server/issues/376.

**Comment by michelleif** [comment] 2020-10-08 18:08
duplicate of #2587 , closing

**Closed by michelleif** 2020-10-08 18:08 UTC
