### ISSUE TITLE
Editor tabs with descriptive naming in heading to support disambiguation

### ISSUE THREAD

**Issue by jimfhahn** [LD4P/sinopia_editor#2813] opened 2021-05-04 16:13 UTC
**Describe the feature you'd like**
Can the record tabs bring in the title or some other disambiguation information? Maybe "title-part-of-the-instance-id-number" in the tab name. If we open multiple of the same type of resource template and want to have those open we can't easily tell which one we are selecting, especially if they have similar data (e.g. if they are multiple items that we want to describe).

<img width="760" alt="Screen Shot 2021-05-04 at 11 07 49 AM" src="https://user-images.githubusercontent.com/1310509/117034712-330fa780-acc9-11eb-92eb-b7d7e20fb817.png">

**Give an example**
Like a web browser tab with the page title.

**Describe alternatives you've considered**
Doesn't seem to have a disambiguation variable in the tab title, just the template name you are using.  If the template is saved then we get a URI. That URI is important, but I feel we aren't able to quickly disambiguate looking at a URI.

**Comment by justinlittman** [comment] 2021-05-04 16:51
How do you know what the title is?

**Comment by jimfhahn** [comment] 2021-05-04 18:24
As a little background to when this is a problem. When someone asks me to troubleshoot something, I usually will need four tabs minimum (2 works and 2 instances). After a while, I have trouble knowing which one is the copy vs something that is not a copy, the tabs all look the same to me once enough tabs are opened. Ways to disambiguate that I am editing the "Copy of" a created entity; and knowing when I am "Editing" a created entity and it is not a copy would be very helpful. However, I have also seen folks with multiple items not being able to distinguish among the two items because they are mostly the same and there are two other tabs open (work, instance, item, item, in the editor for example.)
 
Brainstorming some ways to know what to put in the tab:

- Perhaps a variable from the form as a stand-in for title? Or not a variable from the form, but something like a free text label a cataloger can modify with their own disambiguating own text string?

- A timestamp of when it was opened? Or last viewed/in focus? Or last saved?

-Tabs will have institutional icons of the school in the tab. Helpful if I have copied from another school.

- Randomly, perhaps in addition to naming we could pop-out the tab in a new browser window. I don't know if that would help us manage what we are editing, e.g. we popped out the one we want to keep in focus...

**Comment by michelleif** [comment] 2021-06-22 16:21
duplicate of #2367 ?

**Comment by jimfhahn** [comment] 2021-07-28 16:46
Additional disambiguation support ideas were observed in recent LC BFE updates: for example the use of circle and diamond along with color theming here (though want to make sure distinguishing among Instance and Work is not solely based on color -- e.g. ones that work in greyscale, too)


<img width="821" alt="Screen Shot 2021-07-28 at 11 41 28 AM" src="https://user-images.githubusercontent.com/1310509/127362827-abe23fa0-8faf-4204-b7bf-f549d11ba902.png">

<img width="250" alt="Screen Shot 2021-07-28 at 11 39 03 AM" src="https://user-images.githubusercontent.com/1310509/127362948-1bccde01-0722-404f-941e-f07f749f36d3.png">

<img width="743" alt="Screen Shot 2021-07-28 at 11 39 26 AM" src="https://user-images.githubusercontent.com/1310509/127362988-6000d706-09a3-4822-94b1-da103377177e.png">

**Closed** 2021-10-18 20:45 UTC
Labels: enhancement, Design Needed
