### ISSUE TITLE
All Publication, Distribution, Manufacture, Production Statements' "Place" tooltips, except for Manufacture Activity, lead to the wrong place in RDA Toolkit

### ISSUE THREAD

**Issue by tjkao** [LD4P/sinopia_editor#1220] opened 2019-08-15 14:16 UTC
**Describe the bug**
All tooltips next to Publication/Distribution/Manufacture/Production statements's Place lead to the RDA 2.10.2 Place of Manufacture instead of the correct instruction corresponding to the manifestation element

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
Have to go to RDA Toolkits for the correct instruction. Take additional time.
- What environment are you in? (stage or production)
Stage
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
Windows 7 & 10; Chrome & Firefox
- If you're cataloging, what Resource Template were you using (name or ID)
Sinopia user feedback (ID: Harvard:rt:test:userfeedback)

**Please include a screenshot**
![issue 3](https://user-images.githubusercontent.com/36780916/63100548-4b63ef80-bf45-11e9-83dc-2cdbdba0943b.PNG)

**Comment by jermnelson** [comment] 2019-08-15 14:57
All tooltips are from the `remark` property in property Templates are in resource templates. In this example, the resource template `stanford:RT:BF2:ProvisionPlace` has a remark value of *http://access.rdatoolkit.org/2.10.2.htm*. This is not a bug in the Sinopia codebase but the **remark** property would need to be changed for this propertyTemplate in the `stanford:RT:BF2:ProvisionPlace` resource template.

**Comment by michelleif** [comment] 2019-08-15 15:51
Hi TJ I believe this part of the template was copied from an LC template and on the LC BIBFRAME Editor site, their Place search also goes to that same RDA instruction. 
<img width="598" alt="Screen Shot 2019-08-15 at 8 51 04 AM" src="https://user-images.githubusercontent.com/23069165/63107432-ca532b00-bf39-11e9-9310-1efe59189305.png">
I didn't check the others in that Publication/Distribution/Manufacture/Production section in the LC templates.
I'm going to leave this open and mark it as a template issue, since we will soon be loading the latest LC templates and having people review them and will find similar issues.

**Comment by justinlittman** [comment] 2019-09-10 15:50
Closing this ticket, since not a Sinopia issue.

**Closed by justinlittman** 2019-09-10 15:50 UTC
Labels: BFF, templates
