### ISSUE TITLE
Input lost

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1263] opened 2019-08-19 03:06 UTC
During input of metadata for Instance, I hit a wrong key (Enter, I think) and was thrown out of the Editor, losing all content keyed.  Getting ejected and losing work should not be easy to do.

**Comment by justinlittman** [comment] 2019-09-10 13:40
Can you please write specific steps to reproduce the error? Thanks!

**Comment by michelleif** [comment] 2019-09-13 19:39
@threadleaf i know the user feedback template is gone now so you can't reproduce, but can you let us know what platform (Mac or Windows) and browser you were using?

**Comment by threadleaf** [comment] 2019-09-14 02:54
Windows; either Chrome or Firefox, unfortunately I don’t recall which.  Definitely not IE, I never use that.

MJ Cuneo

**Comment by michelleif** [comment] 2019-09-16 17:37
@threadleaf thanks, i'm going to close this and if you see this happen again on firefox please report with details of what key(s) you pressed that cause the problem

**Closed by michelleif** 2019-09-16 17:37 UTC
Labels: BFF, bug, question

**Comment by threadleaf** [comment] 2019-09-17 15:20
OK

mjc
