### ISSUE TITLE
Incorrect message "Resource has unsaved changes. Are you sure you want to close?" displaying

### ISSUE THREAD

**Issue by CECSpecialistI** [LD4P/sinopia_editor#1998] opened 2019-12-16 23:56 UTC
Closing a saved description in the University of Washington's resource templates results in the message "Resource has unsaved changes. Are you sure you want to close?" when there are in fact no unsaved changes. This happens with both new descriptions and after editing previously-saved descriptions and re-saving.

![image](https://user-images.githubusercontent.com/43214565/70952801-41015180-201c-11ea-97f9-d64b77c46635.png)

**Comment by justinlittman** [comment] 2019-12-17 14:46
@CECSpecialistI Thanks for reporting! I can't reproduce the problem. Can you please provide exact steps to reproduce?

**Comment by CECSpecialistI** [comment] 2019-12-17 17:29
Sure! The problem is in production, if that makes a difference.
Either:
a) Open any WAU resource template, fill out the required fields, save, and hit close
or,
b) Open a WAU description at any level (the one above, "How to train your boxer", works), make some change, save it, and hit close
If that doesn't reproduce the problem, maybe it's an issue with our "group" specifically?

**Comment by justinlittman** [comment] 2019-12-17 19:54
Afraid I still can't reproduce. Can you try a hard refresh and see if it can be replicated?

Assuming that doesn't fix it, what OS are you on? What browser and version?

**Comment by gdegroat** [comment] 2019-12-17 21:32
I am having the same issue.  I am using Firefox 71.0 64 bit on Windows 10 education.  I'm at Stanford,  Here's a screenshot of an instance i created today, apparently successfully saved despite the message, closed and reopened without making changes, then tried to close:

![image](https://user-images.githubusercontent.com/44270367/71036022-aa8f6780-20d1-11ea-9738-580c4f6cc2c7.png)

**Comment by gdegroat** [comment] 2019-12-17 21:35
And here's a work that i created on Nov. 12.  I just opened it, didn't make any changes, and tried to close it.

![image](https://user-images.githubusercontent.com/44270367/71036216-1376df80-20d2-11ea-9b2a-da5ac7ed56cd.png)

**Comment by justinlittman** [comment] 2019-12-18 14:49
This can be reproduced with https://trellis.stage.sinopia.io/repository/stanford/3b9c61b0-0279-4d17-915c-1f1f725ed2ca in Firefox on Mac and Windows.

**Comment by CECSpecialistI** [comment] 2019-12-18 18:33
Sorry for the delay, my kid got sick yesterday. I'm using Firefox Version 71.0 (64-bit) on Windows 10. Hard refresh does not affect the problem.

**Closed** 2019-12-19 00:13 UTC
Labels: BFF, bug
