### ISSUE TITLE
Generate URI for literal value in a Look-up (PCC wish list no. 1)

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2339] opened 2020-08-11 16:52 UTC
**Describe the feature you'd like**
In the current Sinopia lookup components, when a user enters a text that is not found in the authority source, the user is given an option to save the text as a new literal. While the resulting RDF triple is valid, having a literal value in the RDF object role runs counter to the expectation of the property template that the object role contains an URI. The new feature would take the literal value and create a new resource with an URI that is then saved in RDF object role the original resource's triple. 

**Give an example**

![Screen Shot 2020-08-11 at 10 51 03 AM](https://user-images.githubusercontent.com/71847/89925405-99dfb480-dbc0-11ea-903c-03b5d3aafc3a.png)

![Screen Shot 2020-08-11 at 10 48 13 AM](https://user-images.githubusercontent.com/71847/89925246-600eae00-dbc0-11ea-995e-5c900e8e66a8.png)

**Describe alternatives you've considered**

An alternative would be to manually create a new resource in Sinopia for the literal and paste in the new URI in the lookup field to create the correct triple.

**Comment by michelleif** [comment] 2020-08-18 21:02
duplicate of #2142?

**Comment by michelleif** [comment] 2020-08-18 21:09
what is the ideal workflow here?

--cataloger looks up something and doesn't find what is needed
--cataloger establishes the new entity elsewhere (make a new Work in Sinopia, a new person in LCNAF, a new item in Wikidata, etc) and then use the newly established URI. (ideally Sinopia would link to these external entity sources and allow you to propose/create new entity on the spot but I believe this is out of scope of this grant)
--cataloger uses newly established URI which is now available in the lookup to cataloger and anyone else who does a lookup in that source

maybe there is some kind of partial solution we can create towards the ideal rather than ending up with a lot of sinopia URIs where the only thing we know about them is a label and that they are the object of one assertion.

or, we allow creation of on-the-fly URI and don't call it "new literal", we call it "new Sinopia URI" and there is then a way to export all the new Sinopia URIs that are the object of x property, like all the ones that are probably suitable for LCNAF, and send them there.

**Comment by justinlittman** [comment] 2020-08-19 11:22
The ability to enter a manual URI or literal for a lookup has always seemed problematic to me. In most cases, I suspect this will take any application that uses the RDF resource "by surprise" (that is, cause it to break).

The only scenario I can imagine that is sensible is allowing the cataloger to enter a URI for a newly established authority after that authority URI has been minted and before it is available in the lookup. (That is, it has been added to LCNAF, but not propogated to QA.) Also, in this case it makes sense to be able to provide a label for the URI (which we don't currently support.)

**Comment by michelleif** [comment] 2020-11-06 22:18
For next work cycle, consider removing ability to add literals in fields that expect URIs. Changing the title of the ticket accordingly. Need to run this by users.

**Comment by NancyL** [comment] 2021-01-06 01:09
Just removing it is not a good option.
1. For names, not all entities are necessarily eligible to be created in LC NAF or even in Wikidata. This is particularly the case in bib records representing archival collections. There is a longstanding use case for creating local vocabularies (either institution-local or consortia-local)
2. In the case of other entities created as part of LC vocabularies, there is a long lag between submitting the term and it being accepted/rejected, being added to the authority file, and then being put into id.loc.gov. 
3. RDA has always had open lists in which a number of terms are given, but the cataloger is instructed to use something else if nothing applies
4. Not all existing vocabularies we might want to use have URIs
5. Many libraries create local specialized vocabularies for targeted collections.

**Comment by michelleif** [comment] 2021-01-19 22:07
from PCC Linked Data Advisory Committee review of Sinopia training modules: 

> it seems like an antipattern to allow the same property (in this case, rdf:value) to be used for either a URI or literal. It would be better to separate these out into different properties. See, for example, Yale's [Contribution template](https://sinopia.io/editor/Yale:RT:BF2:Agents:Contribution), which uses a separate property for literals (labeled "Authorized Access Point," but just using rdfs:label within the template itself).
> 
would that be a solution?

**Comment by NancyL** [comment] 2021-03-15 23:43
So the point is, this is currently being used for a URI and a literal, and PCC believes this to be incorrect, seeing as these are all object properties and thus cannot take a literal. As I said above, there are open lists that catalogers use and vocabularies that do not have native URIs. Does this mean they can never be used? I suppose this is a possibility, but not a great one.

Not all the terms we might want are intended to be, or can be, created in another vocabulary, even Wikidata.

This issue is no. 1 on PCC's wish list

**Comment by justinlittman** [comment] 2021-03-16 00:42
The user can just create a URI and enter it into the URI field. Does that satisfy the requirement?

**Comment by NancyL** [comment] 2021-03-16 00:52
um, how does one create a URI or at least one that has any meaning? And how do you say what the label should be?
________________________________

**Comment by justinlittman** [comment] 2021-03-16 01:10
I agree that should be able to enter a label when manually enter a URI -- it has always seemed like a gap in Sinopia.

A URI is just a unique identifier. What does it mean for a URI to have meaning?

**Comment by michelleif** [comment] 2021-03-19 21:42
is this a dupe of #1317?

**Comment by NancyL** [comment] 2021-03-19 22:02
To a certain extent, though the conversation is rather different around it.

I have a hard time finding anything in the issues to check for dups

**Comment by michelleif** [comment] 2021-08-05 05:08
see #2843: allow users to enter a label with a URI, and
#2887: disallowing literals in lookup fields

@NancyL please advise once you have checked with your PCC group about whether we can close this ticket

**Comment by NancyL** [comment] 2021-08-05 16:56
This should work as long as it is paired with the ability to add a label.

It will allow catalogers to create an authority in the NAF and then enter the expected URI (since we know what it will be) & label in Sinopia before that URI is officially generated. That will avoid anyone having to return later to change the URI.

And if a cataloger does not for some reason want to create an authority in NAF or Wikidata, we will create a short template for doing so in Sinopia. My only questions here are whether
a. the label will show up in the work/instance template
b. the names will be searchable

**Comment by michelleif** [comment] 2021-08-06 14:49
re creating a person entity via a template in Sinopia, and then doing a lookup in another template in order to use that entity:
I tested it, any literals in the person description are searchable.
But when you do the lookup, the only thing you see about the person is the Sinopia URI, because Sinopia doesn't know what to use for a label when there is no bf or RDA title property. (in this screenshot, the top result is the person I just created in the person template)
<img width="736" alt="Screen Shot 2021-08-06 at 7 41 43 AM" src="https://user-images.githubusercontent.com/23069165/128527792-836eb914-11d6-4c28-9f94-f7fa8bda3eb6.png">
There is a ticket to show context on Sinopia lookups: #2769, which will be done in upcoming work cycle.
There is a ticket #2869 to show labels for things that don't have a BF or RDA title property. We weren't going to approach that one yet but I will move it to "things to do this work cycle."

**Comment by michelleif** [comment] 2021-08-10 21:11
closing this ticket since we have decided to disallow literals in lookup fields, see epic #2896 for this work as well as follow-on tickets for user adding label when entering URI; showing context when searching Sinopia URIs; displaying label for non-title resources in search, etc.

**Closed by michelleif** 2021-08-10 21:11 UTC
Labels: question, pcc
