### ISSUE TITLE
Sign Out does not work on first try (when staying on home page)

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#432] opened 2019-03-21 19:31 UTC
After logging in, clicking Sign Out on home page does not work on first try. You have to click it a second time to actually sign out. Note: if you sign in, then go to the Linked Data Editor page, then back to the home page, then click Sign Out, it works on the first try.

blocked by LD4P/sinopia_server#89

**Comment by mjgiarlo** [comment] 2019-04-10 23:07
After chatting with @jmartin-sul, it seemed like https://github.com/LD4P/sinopia_server/issues/89 was a higher-priority, blocking issue. Unassigning and putting back into the backlog.

**Comment by jmartin-sul** [comment] 2019-05-28 21:36
i'm going to go ahead and close this as a sorta-not-really dupe of #556:  though the problematic behavior ends up being similar, it's not quite the same, and this bug was filed before the login and session management machinery was totally overhauled by #460.  so, my gut feeling is that leaving this issue open is more misleading than illustrative.

feel free to reopen if i'm off base, or if having this open provides some extra value i didn't notice.

**Closed by jmartin-sul** 2019-05-28 21:36 UTC
Labels: bug, good first issue, low priority
