### ISSUE TITLE
Tabbing around screen

### ISSUE THREAD

**Issue by jbaxmeyer** [LD4P/sinopia_editor#1252] opened 2019-08-16 14:38 UTC
While the tabbing order is intuitive, the tabbing highlights all hyperlinks on the page (even the ones "behind the scenes"), so that after you have tabbed out of the form, you have to continue tabbing many many times to get back **to** the form; it seems to be picking up links to external vocabularies, etc.

**Comment by threadleaf** [comment] 2019-08-19 02:07
I had the same experience, here's how I described it:  Although the tab stops are straightforward, they do not immediately seem so, visually.  Blue text is not highlighted when tabbing alights on it, so tabbing "disappears" momentarily; and highlighting around the tooltip for RDA is hard to notice at first so tabbing may seem to disappear for those clicks too.

**Comment by michelleif** [comment] 2019-09-13 22:47
re the tab focus disappearing see #1277 
the other issue seems to be the same as #1256, after you finish tabbing through the form, the tabbing continues into the footer and then header of the page, and that's when it goes to the items on the Help & Resources menu
closing as duplicate of those other 2 tix

**Closed by michelleif** 2019-09-13 22:47 UTC
Labels: BFF, Design Needed, enhancement
