### ISSUE TITLE
Save triple in Load tab for Base URI

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#961] opened 2019-07-15 22:37 UTC
In the **Load** tab we currently use the *Base URI* field to map the base subject URI in the N3 graph but after loading into the Editor, currently we discard this Base URI. Instead, this Base URI value should be the object in a triple with https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasDerivedFrom as the predicate, and the new entity as the object.

**Comment by jcoyne** [comment] 2019-07-16 19:53
I feel like the Load tab was an expansion of scope that was not in the design.  I believe @justinlittman added this as a tool for developers, as at the time we didn't have a way to load saved resources.  It was not intended to be something that we want to bring to production.   Can we clarify that we want to expand the scope here and in the current milestone?

**Comment by jcoyne** [comment] 2019-07-16 20:03
In any case this seems to relate to https://github.com/LD4P/sinopia/issues/45 which is marked as M5, so would it be good to have both in the same milestone?

**Comment by jermnelson** [comment] 2019-07-16 20:14
I agree that this expansion of scope; maybe @michelleif can decided if we expand support for the load within scope for M4. From yesterday's user group meeting, there was enthusiasm for having this load tool available for use by the cohort.

> I feel like the Load tab was an expansion of scope that was not in the design. I believe @justinlittman added this as a tool for developers, as at the time we didn't have a way to load saved resources. It was not intended to be something that we want to bring to production. Can we clarify that we want to expand the scope here and in the current milestone?

**Comment by michelleif** [comment] 2019-07-16 20:25
while this is an expansion of scope for M4, it does expediently meet some use cases that would have had to wait until M5. 

The base URI is insignificant. we do NOT need to retain it as an object. the use case is that people want to populate a form as if they were manually copying and pasting data from another source into several fields. they are NOT asking to retain the connection to the other source.

can we discuss this in storytime? for now we don't need any more work on the load tab, let's let people try it out as is when we push a new release at end of this sprint.

**Comment by michelleif** [comment] 2019-07-17 01:20
@jermnelson I think we should close this. For the "cloning" use case, catalogers simply want to grab data from somewhere to use as boilerplate. Confirmed for Cornell's discogs use case, they want to "sever" the connection with where the data came from.

**Comment by jermnelson** [comment] 2019-07-17 14:36
> The base URI is insignificant. we do NOT need to retain it as an object. the use case is that people want to populate a form as if they were manually copying and pasting data from another source into several fields. they are NOT asking to retain the connection to the other source.
> 
Let's double-check with Harvard, I seem to remember Christina asking about copying a RDF resource into the Load tab from Share-VDE, the Share-VDE URI would be the Base URI and should be captured in the RDF.
 
> can we discuss this in storytime? for now we don't need any more work on the load tab, let's let people try it out as is when we push a new release at end of this sprint.

I agree, I removed the m4 label and moved to the Sinopia Work-Cycle Two project.

**Comment by justinlittman** [comment] 2019-09-10 15:18
Closing for now. After further work on loading, will see if the need for this re-emerges and the requirements are clearer.

**Closed by justinlittman** 2019-09-10 15:18 UTC
Labels: BFF, future
