### ISSUE TITLE
Hover text not rendering

### ISSUE THREAD

**Issue by jsoenyun** [LD4P/sinopia_editor#1598] opened 2019-10-22 17:50 UTC
**Describe the bug**
What went wrong? What did you expect to happen?
Apparently since at least yesterday and perhaps Friday: If a remark in a template is text and not a URL the data editor form no longer displays hover text. The graphic of the "i" in a circle is rendering fine, differently from the graphic for an external link, only no further information is available. This is while using Chrome/Windows.

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue) Moderate importance: most important to have this text in place as useful background information when we train staff to input metadata
- What environment are you in? (stage or production) Stage
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.) Chrome/Windows
- If you're cataloging, what Resource Template were you using (name or ID) UCSD:RT:BF2:RightsModuleTest:Work:CcLicenseModel

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)
![image](https://user-images.githubusercontent.com/13667549/67314507-99532180-f4b9-11e9-8373-7c7044323756.png)

**Comment by michelleif** [comment] 2019-10-22 18:54
another example can be found in DEV, resource template ID Sinopia:RT:Demo:SampleResourceFuller, fields called Example 20 and Example 22

**Comment by justinlittman** [comment] 2019-10-23 20:05
Dupe of #1520.

**Closed by justinlittman** 2019-10-23 20:05 UTC
Labels: BFF, bug

**Comment by justinlittman** [comment] 2019-10-23 20:06
Thanks for reporting @jsoenyun. Fix forthcoming.
