### ISSUE TITLE
newly created resources don't show up in search

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#1343] opened 2019-09-20 15:11 UTC
on stage and on dev, create a new description that has a title.
the new resource does not show up in search results.
examples of resources that should be found in search:

https://trellis.stage.sinopia.io/repository/stanford/c2ea4e49-8399-4459-9088-bd9f1688d9af
https://trellis.development.sinopia.io/repository/stanford/382b2f5e-fb2a-4f2d-a639-c709505021bb

**Comment by justinlittman** [comment] 2019-09-23 12:00
Dupe of https://github.com/LD4P/sinopia_indexing_pipeline/issues/41

**Closed by justinlittman** 2019-09-23 12:00 UTC
Labels: BFF, bug
