### ISSUE TITLE
Failed MARC conversion

### ISSUE THREAD

**Issue by gdegroat** [LD4P/sinopia_editor#2707] opened 2020-11-03 19:39 UTC
Stage, Firefox, Instance template, MARC conversion failed.  This is one of the ones i reported previously that had the duplicated Subclass of Instance which is showing up as an unused triple.  I'm not sure if it's that or something else that is causing the conversion to fail, but i had particularly wanted to test this one because it has two associated Work records and i wanted to see how or if it would handle that.

![image](https://user-images.githubusercontent.com/44270367/98032702-3df48880-1dc9-11eb-9753-cc71636081b9.png)

**Comment by justinlittman** [comment] 2020-11-04 20:55
This is because the subject is ordered, which rdf2marc does not support. Thus, this is a dupe of https://github.com/LD4P/rdf2marc/issues/33.

Closing this ticket since this is covered by other ticket.

**Closed by justinlittman** 2020-11-04 20:55 UTC
Labels: bug
