### ISSUE TITLE
Entering a URL in a lookup field queries QA for the label

### ISSUE THREAD

**Issue by jermnelson** [LD4P/sinopia_editor#2112] opened 2020-03-20 21:42 UTC
**Describe the feature you'd like**
When doing a QA look-up, users have the option to manually enter a URL. QA should then be queried with URL to search for a label and if found persist the label to RDF. 

**Give an example**
Pasting in `http://id.nlm.nih.gov/mesh/D014780` into a subject look-up field, the URL will be persisted with an `rdfs:label` of **Viruses**.

**Describe alternatives you've considered**

**Comment by NancyJean** [comment] 2020-03-23 21:37
Just checking to make sure this works the other way too -- i.e., if you do a search in QA and select a label, under the hood Sinopia should be storing the URI (and perhaps caching the label) for that entity, while displaying the label for humans to read.

**Comment by michelleif** [comment] 2020-03-26 15:22
is this a duplicate of #1227

**Comment by michelleif** [comment] 2020-03-26 15:22
@NancyJean yes Sinopia stores both the URI and the label when you select something from a QA lookup, if you look at Preview you will see both

**Comment by NancyJean** [comment] 2020-03-26 16:07
@michelleif  yes, it does look like the same or at least a very similar issue as #1227

**Comment by michelleif** [comment] 2020-04-22 23:34
duplicate of #1227

**Closed by michelleif** 2020-04-22 23:34 UTC
Labels: BFF, enhancement
