### ISSUE TITLE
cultural organizations codelist look-up hanging

### ISSUE THREAD

**Issue by mmcgee** [LD4P/sinopia_editor#1208] opened 2019-08-14 16:08 UTC
**Describe the bug**
What went wrong? What did you expect to happen?

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
- What environment are you in? (stage or production)
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by mmcgee** [comment] 2019-08-14 16:09
lookup for: https://id.loc.gov/vocabulary/organizations appears to be hanging indefinitely

**Comment by jermnelson** [comment] 2019-08-14 18:12
Hi @mmcgee, the Library of Congress changed how they deliver this data. Before the Sinopia component parsed the uri https://id.loc.gov/vocabulary/organizations.json to extract the codes but now there is a message that these codes are available for bulk download instead at https://id.loc.gov/vocabulary/organizations. 

@michelleif is making a new QA authority request for this source to be available there instead. I'm going to remove this as a source in the Editor and Profile Editor in the meantime. We'll keep this issue open until the QA authority is available.

**Comment by michelleif** [comment] 2019-08-24 20:41
have not made the QA issue yet, comments from @kirkhess via email:
"The org code list has some issues – in general, I think the problem is everyone has a code they use today and have no idea the label to use for the code. The labels have a very tenuous connection to the code plus all the old codes are never deprecated or removed – there 40+ LC codes of which we use 1 (DLC). We were trying to change the suggest service to allow you to type in the code instead of the name, I think that’s the change you mentioned. I think we need to work this issue to fix the list itself as well. A QA list isn’t going to fix this code/label + obsolete code problem."

do we want to spend QA time on taking the bulk download list and making it available via QA given that the list has the issues Kirk describes?

while we are waiting for the list itself to be fixed, we could also just change these fields to literals.

**Comment by justinlittman** [comment] 2019-09-10 15:31
This is no longer hanging, so closing this ticket. If you want to have https://id.loc.gov/vocabulary/organizations available, please make a ticket with QA.

**Closed by justinlittman** 2019-09-10 15:31 UTC
Labels: Authorities
