### ISSUE TITLE
redux state needs to include all URI info from template

### ISSUE THREAD

**Issue by ndushay** [LD4P/sinopia_editor#536] opened 2019-05-20 20:56 UTC
in other words, in order to generate RDF from the redux state and from a property template, currently we would need to do another "get" of the resource template to get things like resourceURI and propertyURI.

**Comment by justinlittman** [comment] 2019-06-03 11:40
Is this duplicate of #604?

**Comment by jcoyne** [comment] 2019-06-03 14:56
@justinlittman I think #604 is a duplicate, but with more direct instructions about what is needed.

**Comment by jermnelson** [comment] 2019-06-03 15:42
This ticket should be more granular with #604 being the first of two elements that need storing in Redux state. The draft PR #569, adds the second with the `rdfProperty` property set for propertyTemplates.

**Closed** 2019-06-12 15:06 UTC
Labels: M4
