### ISSUE TITLE
Tabbing ?)

### ISSUE THREAD

**Issue by JoannaDatSUL** [LD4P/sinopia_editor#1268] opened 2019-08-19 19:17 UTC
Tabbing works fine although the cell with the cursor in it could be more visible (highlighted in a brighter color?)

**Give an example**

**Describe alternatives you've considered**

**Comment by michelleif** [comment] 2019-09-10 00:19
see #1277

**Comment by michelleif** [comment] 2019-09-13 19:51
duplicate of #1277

**Closed by michelleif** 2019-09-13 19:51 UTC
Labels: BFF, duplicate, enhancement
