### ISSUE TITLE
Loading literal with language does not display language

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#1010] opened 2019-07-19 11:00 UTC
Steps to reproduce:
1. Load the following RDF:
```
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Note> .
<> <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:Note" .
<> <http://www.w3.org/2000/01/rdf-schema#label> "foo"@ne .
```

Expected result:
Language code (_ne_) is displayed on the Language button (since the label for the language is not known).

Actual result:
![Screen Shot 2019-07-19 at 6 59 31 AM](https://user-images.githubusercontent.com/588335/61530708-d4454500-a9f2-11e9-82ca-6e0a95fa348f.png)

Bonus points for displaying the correct language.

**Comment by jcoyne** [comment] 2019-07-19 15:00
Duplicate of #1006

**Closed by jcoyne** 2019-07-19 15:00 UTC
Labels: BFF, M4, bug
