### ISSUE TITLE
unclear that Edit button next to Language applies to the field's value, not the language

### ISSUE THREAD

**Issue by threadleaf** [LD4P/sinopia_editor#1257] opened 2019-08-19 02:19 UTC
The placement of the Edit button just to the left of the Language box (in the panel labeled 1. Before we start ...) suggests it controls the editing of Language info, but in fact it affects the other text in that panel, not Language.  To edit Language one has to click on the Language box, not on Edit.  This is counter-intuitive.

**Comment by jermnelson** [comment] 2019-08-19 17:11
Tagging this as an enhancement; this is a design request and not a bug in the editor code base.

**Comment by threadleaf** [comment] 2019-08-19 22:46
True—
mjc

**Comment by michelleif** [comment] 2021-09-19 07:08
new designs in #3011, #3012, #3013 remove "Edit" button and just display the selected language, which can be clicked on to change it, so closing this

**Closed by michelleif** 2021-09-19 07:08 UTC
Labels: enhancement, UX
