### ISSUE TITLE
Error: Cannot read property 'graph' of undefined

### ISSUE THREAD

**Issue by jyssy** [LD4P/sinopia_editor#2743] opened 2020-12-15 20:53 UTC
I cataloged a book to test conversion in Sinopia (stage) [sunny day for flowers], at this [URI](https://api.stage.sinopia.io/resource/ca10bebc-3bce-4656-8ed9-0ebe0fca5d3b). 

I see this error when opening, which also restricts me from editing it (or opening to fix it)

![image](https://user-images.githubusercontent.com/30397506/102271472-14a93b00-3ee5-11eb-8344-045f532d001d.png)

I could try to copy this and create a new Instance, maybe, but what the 'graph' is, is a mystery to me.
is this a bug or my cataloging error?

thank you

**Comment by jyssy** [comment] 2020-12-16 14:30
Update: I created a brand new instance, since that error mentioned above would not let me edit or copy. I created a fresh instance, linked [here](https://api.stage.sinopia.io/resource/dc01b04c-7993-4e08-8586-82275931e112), saved, and then attempted to reopen, which gave me the exact same issue. What is the trouble here? what is this 'graph' of undefined?
thank you

![image](https://user-images.githubusercontent.com/30397506/102361442-d8271f00-3f78-11eb-9640-bc4e49ff48b3.png)

**Comment by jyssy** [comment] 2020-12-16 14:31
This error is also restricting my ability to test the internal converter.

**Comment by justinlittman** [comment] 2021-01-14 22:11
The problem is that we're serializing unexpected RDF. Here's a snippet:
```
   {
      "@id": "_:b34",
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": [
        {
          "@id": "_:b35"
        }
      ],
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#first": [
        {
          "@id": "_:b36"
        }
      ]
    },
    {
      "@id": "_:b35",
      "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest": [
        {
          "@id": "_:b37"
        }
      ]
    },
```

Notice in the first object there is a `#first` and `#rest` but in second only a `#rest`. I believe it is an error to be producing the second case.

**Comment by justinlittman** [comment] 2021-01-14 23:10
This can be reproduced by:
1. Open the `UChicago:RT:bf2:Monograph:Instance` to create a new resource.
2. Add a value for Instance Title > Main Title.
3. Add a value for Transcribed Provider Statement.
4. Save the resource. Note the URI.
5. Refresh the browser to open a clean Sinopia Editor.
6. Search on the URI and open the resource for editing.

**Comment by justinlittman** [comment] 2021-01-14 23:11
The problem is that Sinopia is not correctly serializing ordered properties that have empty subject values.

**Comment by justinlittman** [comment] 2021-01-15 13:12
Fix will be released early next week. Sorry for the delay @jyssy.

**Closed** 2021-01-15 13:37 UTC
Labels: bug

**Comment by jyssy** [comment] 2021-01-19 20:09
Thanks - I am a little slow back to looking at this. but will look at this week.

**Comment by jyssy** [comment] 2021-01-28 20:04
@justinlittman just wanted to let you know that this works (I was kinda delayed getting back to look at this issue, but it looks good and works as you said it would) thank you again! :smile_cat:
