### ISSUE TITLE
Errors in one template are stopping me from opening others

### ISSUE THREAD

**Issue by sfolsom** [LD4P/sinopia_editor#1730] opened 2019-11-11 16:22 UTC
**Describe the bug**
What went wrong? What did you expect to happen?

Errors in one template are stopping me from opening others

- What is the impact on your work?

I have to close out and start over before opening a different Template.

- What environment are you in? (stage or production)

Stage

- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)

Mac/Chrome

- If you're cataloging, what Resource Template were you using (name or ID)

sinopia:resourceTemplate:bf2:Identifiers:LCCN from within CornellSinatra45:Instance.

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

![Screen Shot 2019-11-11 at 10 25 00 AM](https://user-images.githubusercontent.com/8257258/68602996-7511b180-0475-11ea-8336-efb4ed2d9916.png)

**Comment by justinlittman** [comment] 2019-11-11 18:16
@sfolsom Can you please provide exact steps to reproduce? I'm must be missing something.

**Comment by justinlittman** [comment] 2019-11-13 16:14
In stage, :
1. Open CornellSinatra45:Work.
2. Add "Has Bibframe instance".
3. Within that, click Add Identifiers.
An error occurs.
4. Now go back to Resource Templates tab.
5. Try to open an resource template (that should open).

Expected result:
Resource template opens.

Actual result:
Same error as above.

**Comment by justinlittman** [comment] 2019-11-14 17:16
So I'm going to declare this a "fingers crossed", meaning that I think the problem is already fixed in current code. We can re-test after next release.

I also fixed some related defects that testing this revealed.

**Comment by michelleif** [comment] 2019-11-15 18:42
seems fixed on DEV. will keep this open until original reporter can verify on stage

**Comment by justinlittman** [comment] 2019-11-18 15:53
@sfolsom Can you verify if this is fixed?

**Comment by sfolsom** [comment] 2019-11-18 16:17
I fixed the error in the profile that was was causing other profiles not to open, so it was hard to recreate the problem. I did find another error in the same set of profiles that doesn't cause other profiles open, so maybe it's fixed. Off to fix the other errors in my profiles...

**Comment by justinlittman** [comment] 2019-11-18 16:40
Feel free to re-open if necessary.

**Closed** 2019-11-18 16:40 UTC
Labels: BFF, bug, fingers crossed :crossed_fingers:
