### ISSUE TITLE
Lookup Bug

### ISSUE THREAD

**Issue by ctenor** [LD4P/sinopia_editor#1217] opened 2019-08-14 22:20 UTC
I cannot page down the entire list of choices (e.g., lcsh or naf lists); the cursor bounces back to the top of the drop down list after 2-3 terms so I have to click with the mouse to get to the desired term further down the list

**Comment by michelleif** [comment] 2019-08-14 22:28
Hi @ctenor can you look at this issue and let me know if this sounds like what you are describing? https://github.com/LD4P/sinopia_editor/issues/1173 
if not, can you include a screenshot so we can better troubleshoot?

**Comment by ctenor** [comment] 2019-08-15 15:48
Yes, we are describing the same issue. Thank you!

**Comment by ctenor** [comment] 2019-08-15 16:27
Hi Michelle,

I will answer this and further questions in github. It might be nice to have a comment section about things we liked so that it doesn’t seem that all our feedback is negative. I assume that if we test something, for example diacritics, and it works, no comment will imply that that functionality is functioning.

I started to input a sheet map, which was not appropriate since it’s not a cartographic profile; it turned into a silly example simply to test functionality. I can describe a real resource if you prefer, though I suppose that’s not the point of the exercise.

Best,

Craig

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Craig Thomas
Senior Cataloger
Information and Technical Services
Harvard Library
625 Massachusetts Avenue
Cambridge, MA  02139
Voice: 617-384-7158
Fax: 617-384-7170
Email: cthomas@fas.harvard.edu<mailto:cthomas@fas.harvard.edu>
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by michelleif** [comment] 2019-08-24 21:10
duplicate of #1173

**Closed by michelleif** 2019-08-24 21:10 UTC
Labels: BFF, bug, duplicate
