### ISSUE TITLE
Additional selections from InputListLOC are no longer added to redux resource state

### ISSUE THREAD

**Issue by jgreben** [LD4P/sinopia_editor#772] opened 2019-06-19 04:35 UTC
"In this ticket I am noting a bug that the changing or adding of new selections are not being propagated to the redux state as { items: [] } for the property node."

**Comment by jcoyne** [comment] 2019-06-19 14:25
@jgreben Can you provide a pointer to a property template that uses this?

**Comment by jgreben** [comment] 2019-06-19 16:19
@jcoyne yes, the spoofed `resourceTemplate:bf2:Monograph:Instance` uses this for `http://id.loc.gov/ontologies/bibframe/carrier`, `http://id.loc.gov/ontologies/bibframe/issuance`, and `http://id.loc.gov/ontologies/bibframe/frequency`.

**Comment by jcoyne** [comment] 2019-06-19 18:03
@jgreben is this a duplicate of #694

**Comment by jgreben** [comment] 2019-06-19 18:16
> @jgreben is this a duplicate of #694 ?

@jcoyne I don't think so. #694 looks to me like a refactoring change to fetch the property template and its default values from redux state rather than having a property template passed down as props from it's parent. In this ticket I am noting a bug that the changing or adding of new selections are not being propagated to the redux state as `{ items: [] }` for the property node.

**Comment by ndushay** [comment] 2019-07-03 01:06
ran locally;  changed carrier, but redux state did not change:

![image](https://user-images.githubusercontent.com/96775/60555999-24828e80-9cf4-11e9-9841-ae22298f5d5f.png)

**Comment by ndushay** [comment] 2019-07-03 23:10
I have spent a few hours on this;  I have determined that:

- i don't know how the component is supposed to know the corresponding URI to the selected literal from the pulldown, as it isn't in the HTML presented for the pulldown ... thus making it impossible to put the URI for selections into redux unless it's the default

- we have no existing tests for `InputListLOC` component sending info to redux
- getting a unit test to mock what is happening with Typeahead component, which is in charge of the actual info in the selection pulldown, seems beyond me, at least before I go on vacation
- this may have some overlap with #832 - mock network calls to QA - as we don't really want to do network calls to do this testing
- if the above can't be suitably mocked for this component unit test ... then tests become  integration tests with the same mocking needs, no?

**Comment by ndushay** [comment] 2019-07-03 23:30
I don't believe we ever get to the `reducers/inputs.js` function `setItemsOrSelections()`

**Comment by ndushay** [comment] 2019-07-04 00:12
code fixed with #890;  test(s) not written.

**Comment by jermnelson** [comment] 2019-07-12 15:45
Closing; fixed in master.

**Closed by jermnelson** 2019-07-12 15:45 UTC
Labels: BFF, M4, bug
