### ISSUE TITLE
Deleting a panel property changes order

### ISSUE THREAD

**Issue by justinlittman** [LD4P/sinopia_editor#2461] opened 2020-09-11 17:50 UTC
Steps to reproduce:
1. Open Uber template1.
2. Click Add next to "Uber template1, property1".
3. Click trash can next to "Uber template1, property1".

Expected result:
"Uber template1, property1" panel appears in existing position (first).

Actual result:
"Uber template1, property1" panel appears in different position (last).

![image](https://user-images.githubusercontent.com/588335/92956944-be37e680-f435-11ea-84e7-858b7d346f3d.png)

**Comment by peetucket** [comment] 2020-09-18 16:53
I think this may be fixed by #2491

**Comment by peetucket** [comment] 2020-09-18 16:55
Indeed, it makes sense based on the changes made in that PR that this would no longer happen.  I also cannot reproduce on my laptop running that branch.

**Comment by jermnelson** [comment] 2020-09-18 17:11
> Indeed, it makes sense based on the changes made in that PR that this would no longer happen. I also cannot reproduce on my laptop running that branch.

Nice when that happens!

**Comment by peetucket** [comment] 2020-09-21 16:08
fixed by #2491

**Closed by peetucket** 2020-09-21 16:08 UTC
Labels: bug
