### ISSUE TITLE
Firefox only: hitting delete button in a QA lookup field to remove a value has same effect as browser back button

### ISSUE THREAD

**Issue by michelleif** [LD4P/sinopia_editor#581] opened 2019-05-29 22:15 UTC
In Editor, in a lookup field that uses QA, when the user hits the "delete" key with the intention of backspacing to remove one of the previously selected values (or to remove the last typed character in a type ahead), it's as if you hit the browser back button. You are taken off of the cataloging screen and back to the list of Resource Templates.
[delete_key.swf.zip](https://github.com/LD4P/sinopia_editor/files/3234661/delete_key.swf.zip)

**Comment by jermnelson** [comment] 2019-05-29 22:32
I was able to replicate this problem only in Firefox; when using Chrome or Safari hitting the delete button works how you expect and just removes the character or the selected entry.

**Comment by michelleif** [comment] 2019-05-29 22:35
thanks @jermnelson for full browser testing! will revise name of issue to indicate firefox-specific

**Comment by mjgiarlo** [comment] 2019-05-29 22:51
I could not reproduce using Firefox 67.0 on Ubuntu Linux. Could be Firefox-on-OSX-only behavior?

@michelleif @jermnelson 	how should we prioritize? this is currently in the backlog and not assigned to a milestone.

**Comment by michelleif** [comment] 2019-05-29 22:55
low priority given that people can use other browsers and given that we've got lots of other stuff to do

**Closed** 2019-08-02 16:50 UTC
Labels: BFF, bug
