### ISSUE TITLE
Information disappeared

### ISSUE THREAD

**Issue by ctenor** [LD4P/sinopia_editor#1214] opened 2019-08-14 22:14 UTC
My preferred work title disappeared and had to be reentered even though it had appeared in "blue" before which would indicate that it had been successfully added.

**Comment by michelleif** [comment] 2019-08-14 22:29
can you list the steps you did, or give more information about when the preferred work title disappeared?

**Comment by ctenor** [comment] 2019-08-15 16:19
I typed in a title and hit Enter. The title appeared in blue in the light blue box. At a later point, after I had added further information to other fields, I noticed the title had disappeared, and I don't believe it was in the underlying rdf. This was also the case, by the way, with my original answer to question 1; it too had disappeared. In the current iteration, however, they have persisted. I should point out, however, that two of my additional contributors and their corresponding relationship designators entered last night have since disappeared from the interface but _not_ from the underlying rdf: the imaginary editor and composer, "Passacaglia, Emilio" and the contributor, Jane Austen (entered as a URL: http://id.loc.gov/authorities/names/n79032879). In the rdf they are alive and well.

This was the rdf which has remained stable:
<> <http://fakepropertyforusertesting1> "If it's working correctly, you should see a different button get highlighted every time you press the tab key."@en .
<> <http://fakepropertyforusertesting1> "Oui, c'est Très  bien."@fr .
<> <http://fakepropertyforusertesting2> "Thanks for testing!"@en .
<> <http://id.loc.gov/ontologies/bibframe/contribution> _:c14n16 .
<> <http://id.loc.gov/ontologies/bibframe/contribution> _:c14n17 .
<> <http://id.loc.gov/ontologies/bibframe/contribution> _:c14n3 .
<> <http://id.loc.gov/ontologies/bibframe/hasInstance> _:c14n14 .
<> <http://id.loc.gov/ontologies/bibframe/subject> <http://id.loc.gov/authorities/subjects/sh85096148> .
<> <http://id.loc.gov/ontologies/bibframe/title> _:c14n21 .
<> <http://sinopia.io/vocabulary/hasResourceTemplate> "Harvard:rt:test:userfeedback" .
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Work> .
_:c14n0 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:resourceTemplate:bf2:Extent" .
_:c14n0 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Extent> .
_:c14n0 <http://www.w3.org/2000/01/rdf-schema#label> "50 pages"@en .
_:c14n1 <http://id.loc.gov/ontologies/bibframe/heldBy> <http://id.loc.gov/vocabulary/organizations/cst> .
_:c14n1 <http://id.loc.gov/ontologies/bibframe/identifiedBy> _:c14n22 .
_:c14n1 <http://id.loc.gov/ontologies/bibframe/identifiedBy> _:c14n5 .
_:c14n1 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Monograph:Item" .
_:c14n1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Item> .
_:c14n10 <http://id.loc.gov/ontologies/bibframe/source> _:c14n13 .
_:c14n10 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:Local" .
_:c14n10 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Local> .
_:c14n10 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "1232498789"@en .
_:c14n11 <http://id.loc.gov/ontologies/bibframe/qualifier> "paperback"@en .
_:c14n11 <http://id.loc.gov/ontologies/bibframe/status> "incorrect"@en .
_:c14n11 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:ISBN" .
_:c14n11 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Isbn> .
_:c14n11 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "1628111011"@en .
_:c14n12 <http://sinopia.io/vocabulary/hasResourceTemplate> "lc:RT:bf2:Agent:Role" .
_:c14n12 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Role> .
_:c14n12 <http://www.w3.org/2000/01/rdf-schema#label> "composer"@en .
_:c14n13 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:Source" .
_:c14n13 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Source> .
_:c14n13 <http://www.w3.org/2000/01/rdf-schema#label> "Alma control number"@en .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/carrier> <http://id.loc.gov/vocabulary/carriers/nc> .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/copyrightDate> "2015"@en .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/dimensions> "25 cm"@en .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/editionStatement> "8th edition, revised"@en .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/extent> _:c14n0 .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/hasItem> _:c14n1 .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/identifiedBy> _:c14n10 .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/identifiedBy> _:c14n11 .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/identifiedBy> _:c14n18 .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/identifiedBy> _:c14n20 .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/issuance> <http://id.loc.gov/vocabulary/issuance/mono> .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/media> <http://id.loc.gov/vocabulary/mediaTypes/n> .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/provisionActivity> _:c14n7 .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/provisionActivityStatement> "Boston : PBS Press, 2015."@en .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/responsibilityStatement> "Madonna."@en .
_:c14n14 <http://id.loc.gov/ontologies/bibframe/title> _:c14n15 .
_:c14n14 <http://sinopia.io/vocabulary/hasResourceTemplate> "Harvard:rt:test:userfeedback:instance" .
_:c14n14 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Instance> .
_:c14n15 <http://id.loc.gov/ontologies/bibframe/mainTitle> "The wizard of OZ revisted"@en .
_:c14n15 <http://id.loc.gov/ontologies/bibframe/note> _:c14n2 .
_:c14n15 <http://id.loc.gov/ontologies/bibframe/partName> "Dorothy's shoes"@en .
_:c14n15 <http://id.loc.gov/ontologies/bibframe/partNumber> "part one"@en .
_:c14n15 <http://id.loc.gov/ontologies/bibframe/subtitle> "a series of compendia"@en .
_:c14n15 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:resourceTemplate:bf2:Title" .
_:c14n15 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
_:c14n16 <http://id.loc.gov/ontologies/bibframe/agent> "Passacaglia, Emilio" .
_:c14n16 <http://id.loc.gov/ontologies/bibframe/role> _:c14n12 .
_:c14n16 <http://id.loc.gov/ontologies/bibframe/role> _:c14n4 .
_:c14n16 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:RT:userfeedback:Agents:Contribution" .
_:c14n16 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Contribution> .
_:c14n17 <http://id.loc.gov/ontologies/bibframe/agent> <http://id.loc.gov/authorities/names/n79089462> .
_:c14n17 <http://id.loc.gov/ontologies/bibframe/role> _:c14n19 .
_:c14n17 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:RT:userfeedback:Agents:Contribution" .
_:c14n17 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Contribution> .
_:c14n18 <http://id.loc.gov/ontologies/bibframe/qualifier> "(paperback)"@en .
_:c14n18 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:ISBN" .
_:c14n18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Isbn> .
_:c14n18 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "9781628111019"@en .
_:c14n19 <http://sinopia.io/vocabulary/hasResourceTemplate> "lc:RT:bf2:Agent:Role" .
_:c14n19 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Role> .
_:c14n19 <http://www.w3.org/2000/01/rdf-schema#label> "cartographer"@en .
_:c14n2 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:resourceTemplate:bf2:Title:Note" .
_:c14n2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Note> .
_:c14n2 <http://www.w3.org/2000/01/rdf-schema#label> "Love me some Lollipop Guild!"@en .
_:c14n20 <http://id.loc.gov/ontologies/bibframe/source> _:c14n8 .
_:c14n20 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:Local" .
_:c14n20 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Local> .
_:c14n20 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "9380928309"@en .
_:c14n21 <http://id.loc.gov/ontologies/bibframe/mainTitle> "Test title qui est Très bien."@fr .
_:c14n21 <http://sinopia.io/vocabulary/hasResourceTemplate> "Harvard:rt:test:userfeedback:worktitle" .
_:c14n21 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Title> .
_:c14n22 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:Barcode" .
_:c14n22 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Barcode> .
_:c14n22 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "alma19879"@en .
_:c14n3 <http://id.loc.gov/ontologies/bibframe/agent> <http://id.loc.gov/authorities/names/n79032879> .
_:c14n3 <http://sinopia.io/vocabulary/hasResourceTemplate> "sinopia:RT:userfeedback:Agents:Contribution" .
_:c14n3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Contribution> .
_:c14n4 <http://sinopia.io/vocabulary/hasResourceTemplate> "lc:RT:bf2:Agent:Role" .
_:c14n4 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Role> .
_:c14n4 <http://www.w3.org/2000/01/rdf-schema#label> "editor"@en .
_:c14n5 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:LC" .
_:c14n5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/ShelfMarkLcc> .
_:c14n5 <http://www.w3.org/1999/02/22-rdf-syntax-ns#value> "PN1503 .B55 2015x"@en .
_:c14n6 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:ProvisionName" .
_:c14n6 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Agent> .
_:c14n6 <http://www.w3.org/2000/01/rdf-schema#label> "PBS Press"@en .
_:c14n7 <http://id.loc.gov/ontologies/bibframe/agent> _:c14n6 .
_:c14n7 <http://id.loc.gov/ontologies/bibframe/date> "2015"@en .
_:c14n7 <http://id.loc.gov/ontologies/bibframe/place> _:c14n9 .
_:c14n7 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:PublicationInfo" .
_:c14n7 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Publication> .
_:c14n8 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:Identifiers:Source" .
_:c14n8 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Source> .
_:c14n8 <http://www.w3.org/2000/01/rdf-schema#label> "OCLC control number"@en .
_:c14n9 <http://sinopia.io/vocabulary/hasResourceTemplate> "stanford:RT:BF2:ProvisionPlace" .
_:c14n9 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Place> .
_:c14n9 <http://www.w3.org/2000/01/rdf-schema#label> "Boston"@en .

**Comment by ctenor** [comment] 2019-08-15 16:49
![image](https://user-images.githubusercontent.com/5302543/63111174-224e5980-bf5b-11e9-824f-5bd50a0cc633.png)

**Comment by ctenor** [comment] 2019-08-15 16:57
![image](https://user-images.githubusercontent.com/5302543/63111471-bae4d980-bf5b-11e9-88ec-f720262b135a.png)

(Contributors opened). I have to say the interface is very confusing with regard to what contributions, agents, and roles, are open or closed (and can be removed) versus those that are empty and can be added. It's very easy to think that data has been lost when it hasn't been. We need to make sure that people don't add data a second time because of the interface.

**Comment by michelleif** [comment] 2019-08-24 21:05
thanks for the feedback. marking this as "Design Needed" so that UX designer can look at it if we work on this in the next work cycle. Maybe some indication that a collapsed field has data in it?

**Comment by justinlittman** [comment] 2019-09-10 15:36
This will be addressed by #1300, so closing this ticket. If in the future, it is still a problem, please re-ticket.

**Comment by michelleif** [comment] 2019-09-13 22:57
I don't see where in #1300 there is a design change that would indicate that user-entered info is present in a collapsed section

**Comment by michelleif** [comment] 2019-09-13 22:58
duplicate of #1249

**Closed by michelleif** 2019-09-13 22:58 UTC
Labels: BFF, Design Needed, enhancement
